# Generated by Django 5.0.2 on 2024-03-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
    ]
