# Generated by Django 5.0.2 on 2024-03-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_pacientes_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='cpf',
        ),
    ]
