# Generated by Django 5.0.2 on 2024-03-04 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_remove_pacientes_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('percentual_gordura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentual_musculo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterol_hdl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterol_ldl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterol_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trigliceridios', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
            ],
        ),
    ]
