# Generated by Django 5.0.2 on 2024-03-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_dadospaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_hdl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_ldl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='percentual_gordura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='percentual_musculo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='trigliceridios',
            field=models.IntegerField(),
        ),
    ]
